### ISSUE TITLE
Crash when placing hanging sign if Amendments mod is loaded

### ISSUE THREAD

**Issue by MaxWasUnavailable** [Alexthw46/Eidolon-Repraised#53] opened 2024-03-01 00:44 UTC
```
Error: java.lang.ClassCastException: class elucent.eidolon.common.tile.HangingSignBlockEntityCopy cannot be cast to class net.mehvahdjukaar.amendments.common.ExtendedHangingSign (elucent.eidolon.common.tile.HangingSignBlockEntityCopy is in module eidolon@1.20.1-0.3.8.1 of loader 'TRANSFORMER' @3b1137b0; net.mehvahdjukaar.amendments.common.ExtendedHangingSign is in module amendments@1.20-1.1.1 of loader 'TRANSFORMER' @3b1137b0)
```

eidolon: 1.20.1-0.3.8.1
amendments: 1.20-1.1.1

**Comment by DahliaDesac** [comment] 2024-03-25 12:10
I think it may be related

**amendments: 1.20-1.1.7
& eidolon 1.20.1-0.3.8.8**
When I try to log on a server with thoses mods I get an Internal Exception io.netty.handler.codec.DecoderException and the server says this for every sign : 

[25.03 11:56:56] [Server] [Server thread/WARN] [minecraft/LevelChunk]: Block entity minecraft:sign @ BlockPos{x=-100, y=66, z=10} state Block{minecraft:spruce_wall_sign}[facing=north,waterlogged=false] invalid for ticking:
[25.03 11:56:56] [Server] [Server thread/WARN] [minecraft/LevelChunk]: Block entity minecraft:sign @ BlockPos{x=-100, y=64, z=10} state Block{minecraft:spruce_wall_sign}[facing=north,waterlogged=false] invalid for ticking:
[25.03 11:56:56] [Server] [Server thread/WARN] [minecraft/LevelChunk]: Block entity minecraft:sign @ BlockPos{x=-97, y=63, z=7} state Block{minecraft:birch_sign}[rotation=7,waterlogged=false] invalid for ticking:

I tried to load a solo world with only thoses 2 mods and everything worked except the sign were invisibles.

**Comment by Alexthw46** [comment] 2024-03-25 14:19
Damn, i'll try to hotfix this asap as it seems to make other signs behave weirdly instead of fixing the eidolon ones

**Comment by Alexthw46** [comment] 2024-03-25 14:49
Try to update asap to https://www.curseforge.com/minecraft/mc-mods/eidolon-repraised/files/5210441 and tell me

**Comment by DahliaDesac** [comment] 2024-03-26 11:48
I tried with amendments 3.1.7 and 3.1.11 on a solo world and everything seems fine :)
But server related (with many more mods sorry) : 
- with 3.1.7 the server keeps returning an Internal Exception io.netty.handler.codec.DecoderException when trying to log in (without the sign logs tho).
- and with 3.1.11, the server can't even start, here is the [latest.log](https://gist.github.com/Reikounet/591a398c3b17d06622c68248561b5452) if it can help 👀

**Comment by Alexthw46** [comment] 2024-03-26 12:55
Double check that the dependencies of Amendments are up to date, cause the log would suggest that. I'll try later to check the decoder exception cause it can be anything

**Comment by DahliaDesac** [comment] 2024-03-27 08:59
Oh sorry, I'm not very useful here 😬
But I keep getting the error even after updating the dependencies, here is the [log](https://gist.github.com/Reikounet/0a72a6b1faf128c9074fc7a834524abd).

**Comment by Alexthw46** [comment] 2024-03-27 09:57
That says the server started successfully tho? So only the connection error remains right?

**Comment by DahliaDesac** [comment] 2024-03-27 10:47
Yeah exactly !

**Comment by Alexthw46** [comment] 2024-03-27 17:51
Sad news is that i can't reproduce that, on my server it works and let me connect to it must be more complex than just two mods not collaborating. The decoder exceptions are extremely annoying cause no good error report is made but it simply fails

**Comment by DahliaDesac** [comment] 2024-03-27 18:17
Ok i see, I'll report here if I can find anything else :)

**Comment by Alexthw46** [comment] 2024-03-27 18:57
https://www.curseforge.com/minecraft/mc-mods/spit-it-out try adding this ?

**Comment by Alexthw46** [comment] 2024-03-31 17:02
closing this as the decoder bug is actually #60

**Closed as completed by Alexthw46** 2024-03-31 17:02 UTC
