### ISSUE TITLE
[1.20.1] minor graphics issues and necromancer a.I. stuff

### ISSUE THREAD

**Issue by Yay4** [Alexthw46/Eidolon-Repraised#36] opened 2023-12-28 23:35 UTC
the bone paladin gear doesn't take into account skin layers
the giant skeleton isn't holding the sword right
the necromancers skeletons don't attack they just walk around (I don't know if thats intended or this is a work in progress {the necromancer is neutral also but I don't know if this is just intended})

**Comment by Alexthw46** [comment] 2023-12-29 10:15
for the necromancer thing, it seems to be coded (as in, legacy code) to not be hostile to players with at least 50 devotion points with the dark deity. Unsure on whether to keep, it should at least fight back if hit, if not then i'll have to look into it

**Comment by Yay4** [comment] 2024-01-05 22:16
oh ok the necromancer does fight back when hit but his skeletons don't

**Comment by Alexthw46** [comment] 2024-01-14 17:37
yeah, bug confirmed and hopefully fixed in-dev. the targeting code was not accounting for non-players

**Closed as completed** 2024-01-25 17:23 UTC
