### ISSUE TITLE
"Rendering screen" crash after looking at brazier recipes with JEI

### ISSUE THREAD

**Issue by mosharky** [Alexthw46/Eidolon-Repraised#7] opened 2023-10-20 04:22 UTC
The crash happens with any brazier recipe, with the error: "java.lang.IllegalStateException: Not building!"

Eidolon: v0.3.5.3
Minecraft: v1.20.1
Forge: v47.2.1
Crash: https://mclo.gs/MoZeHwA

**Comment by Alexthw46** [comment] 2023-10-20 08:35
Duplicate of #5 basically. Incompatibile with ImmediatelyFast until the bufferbuilder thing is sorted out.

**Comment by Alexthw46** [comment] 2023-10-20 08:36
Duplicate of #5 basically. Incompatibile with ImmediatelyFast until the bufferbuilder thing is sorted out.

**Closed as completed by Alexthw46** 2023-10-20 08:35 UTC

**Comment by mosharky** [comment] 2023-10-20 15:47
ah sorry, i wasnt aware that mod was related to that crash
