### ISSUE TITLE
Suggestion: Allow the Ars Ecclesia to be able to be placed on Lecterns

### ISSUE THREAD

**Issue by SynfulChaot** [Alexthw46/Eidolon-Repraised#58] opened 2024-03-17 07:30 UTC
It would be useful if we could read the Ars Ecclesia from a Lectern to free up an inventory spot when we're working in the same place for a while.  Also because it'd just be pretty cool.

**Comment by Alexthw46** [comment] 2024-03-17 09:38
Dupe of #49 added but not yet released

**Closed as completed by Alexthw46** 2024-03-17 09:38 UTC
